### PR TITLE
Fix building on FreeBSD

### LINKED ISSUE #941: [FreeBSD] Compilation of libfuse fails on FreeBSD due to an unrecognized type/codes
FAILED: example/notify_inval_inode.p/notify_inval_inode.c.o
cc -Iexample/notify_inval_inode.p -Iexample -I../example -Iinclude -I../include -Ilib -I../lib -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -D_REENTRANT -DHAVE_LIBFUSE_PRIVATE_CONFIG_H -Wno-sign-compare -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -pthread -MD -MQ example/notify_inval_inode.p/notify_inval_inode.c.o -MF example/notify_inval_inode.p/notify_inval_inode.c.o.d -o example/notify_inval_inode.p/notify_inval_inode.c.o -c ../example/notify_inval_inode.c
**../example/notify_inval_inode.c:289:44: error: use of undeclared identifier 'EBADFD'**
                 ret != -ENOENT && ret != -EBADFD && ret != -ENODEV) {

.**/example/notify_store_retrieve.c:355:43: error: use of undeclared identifier 'EBADFD'**
                ret != -ENOENT && ret != -EBADFD && ret != -ENODEV) {

[20/62] Compiling C object example/hello_ll_uds.p/hello_ll_uds.c.o
../example/hello_ll_uds.c:287:11: **warning: implicit declaration of function 'splice' is invalid in C99** [-Wimplicit-function-declaration]
                int i = splice(fdin, offin, fdout, offout, len - count, flags);

2/13] Compiling C object test/test_write_cache.p/test_write_cache.c.o
FAILED: test/test_write_cache.p/test_write_cache.c.o
cc -Itest/test_write_cache.p -Itest -I../test -Iinclude -I../include -Ilib -I../lib -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -D_REENTRANT -DHAVE_LIBFUSE_PRIVATE_CONFIG_H -Wno-sign-compare -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -pthread -MD -MQ test/test_write_cache.p/test_write_cache.c.o -MF test/test_write_cache.p/test_write_cache.c.o.d -o test/test_write_cache.p/test_write_cache.c.o -c ../test/test_write_cache.c
.**./test/test_write_cache.c:217:5: error: unknown type name 'loff_t'; did you mean 'off_t'?**
    loff_t off = 0;
    ^~~~~~

### PR DESCRIPTION
**Pull request by CismonX**
Fixed some minor issues in examples which prevents them from building successfully on FreeBSD.

Should be able to close #941.

### CODE REVIEW

File: example/notify_inval_inode.c [hunk 1]
```diff
@@ -287,14 +287,14 @@ static void* update_fs_loop(void *data) {
...
+            /* Some errors (ENOENT, EBADF, ENODEV) have to be accepted as they
              * might come up during umount, when kernel side already releases
              * all inodes, but does not send FUSE_DESTROY yet.
              */
             int ret =
                 fuse_lowlevel_notify_inval_inode(se, FILE_INO, 0, 0);
             if ((ret != 0 && !is_stop) &&
-                 ret != -ENOENT && ret != -EBADFD && ret != -ENODEV) {
+                 ret != -ENOENT && ret != -EBADF && ret != -ENODEV) {
                 fprintf(stderr,
```
Comment (bsbernd) [inline example/notify_inval_inode.c:298]: I don't think that is going to work - issue is that linux sends EBADFD here. It took me quite a while to fix these random unit test failures here. 
Do you know if FreeBSD kernel supports notifications at all?

**Comment by bsbernd** [comment]
@CismonX Thank you very much! I think we just to find a different solution for EBADFD, I wonder if FreeBSD supports that at all. If it does, we need to add a `__linux__` condition, if not, the test could just get disabled?

File: example/notify_inval_inode.c (hunk 1 above)
Comment (bsbernd) [reply example/notify_inval_inode.c:298]: Yeah, you are right, there is not much that sends EBADFD, I'm going to double check. Reproducer for the github issues was a sleep in the loop - going to try that in the morning. 
If this is indeed a type, I wonder why test does not fail anymore, hmm.

Comment (bsbernd) [reply example/notify_inval_inode.c:298]: Sorry, got sick last Friday. When I just wanted to look into it now, I run into a new issue (see https://github.com/libfuse/libfuse/issues/979), need to look into that first.

Comment (bsbernd) [reply example/notify_inval_inode.c:298]: User error on my side, forgot to give the mount point, but still no reason to segfault inside of libfuse.
Tested it now, yeah, you are absolutely right, the error is actually `EBADF`. Interesting how it always passed tests - I had added that check to avoid random ci failures.

**Review by bsbernd — APPROVED** [review]

**Comment by bsbernd** [comment]
@CismonX Thanks again, merged!
